export const FETCH_PRODUCTS_GENDER = 'FETCH_ALL_PRODUCTS_GENDER'
export const SEARCH = 'SEARCH'
export const FETCH_PRODUCTS_CATEGORY = 'FETCH_PRODUCT_CATEGORY'
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT'